backend:
  name: git-gateway
  branch: main

media_folder: 'src/assets/images'
public_folder: '/_astro'

collections:
  - name: 'post'
    label: 'مقال'
    folder: 'src/content/post'
    create: true
    fields:
      - { label: 'عنوان', name: 'title', widget: 'string' }
      - { label: 'اقتباس', name: 'excerpt', widget: 'string' }
      - { label: 'فئة', name: 'category', widget: 'string' }
      - {
          label: 'أوسمة',
          name: 'tags',
          widget: 'list',
          allow_add: true,
          allow_delete: true,
          collapsed: false,
          field: { label: 'وسم', name: 'tag', widget: 'string' },
        }
      - { label: 'صورة', name: 'image', widget: 'string' }
      - { label: 'تاريخ النشر', name: 'publishDate', widget: 'datetime', required: false }
      - { label: 'الكاتب', name: 'author', widget: 'string' }
      - { label: 'المحتوى', name: 'body', widget: 'markdown' }
